import React from 'react'
import { createBrowserRouter, Navigate } from 'react-router'
import type { RouteObject } from 'react-router'
import BasicLayout from '@/layouts/BasicLayout'
import AuthGuard from './authGuard'
import Login from '@/pags/Login'
